# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ivan Pik - Web Designer and Front-End Developer
email: contact@ivanpik.co.uk
location: Bristol, UK
availability: Available for a full-time position
description: Portfolio of a Web Designer and Front-End Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ivanpik.co.uk" # the base hostname & protocol for your site


# Build settings
markdown: kramdown


# Defaults
defaults:
  -
    scope:
      path: "projects"
    values:
      layout: "project"

# Glynn Set Up
ftp_host: 'ftp.ivanpik.co.uk'
ftp_dir: '/subdomains/new/'
ftp_passive: false